on:
  push:
    branches:
      - develop
      - epic/**
      - release/**
      - feature/**
      - integration-libs/**
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}

name: Spartacus CI pipeline
jobs:
  unit_tests_core:
    name: Unit tests for core Spartacus libs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - name: Install angular CLI
        run: npm install -g @angular/cli@v12-lts
      - name: Package installation
        run: yarn --frozen-lockfile
      - name: Run unit tests for core Spartacus libs
        run: ci-scripts/unit-tests-core-lib.sh
  unit_tests_libs:
    name: Unit tests for integration libs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - name: Install angular CLI
        run: npm install -g @angular/cli@v12-lts
      - name: Package installation
        run: yarn --frozen-lockfile
      - name: Run unit tests for integration libs
        run: ci-scripts/unit-tests.sh
  linting:
    name: Validation checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - name: Install angular CLI
        run: npm install -g @angular/cli@v12-lts
      - name: Package installation
        run: yarn --frozen-lockfile
      - name: Validate linting
        run: ci-scripts/validate-lint.sh
  b2c_e2e_tests_1:
    name: E2E tests for B2C, 1st job
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Run e2es
        env:        
          SPA_ENV: ci,b2c
        run: | 
          ci-scripts/e2e-cypress.sh        
  b2c_e2e_tests_2:
    name: E2E tests for B2C, 2nd job
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Run e2es
        env:         
          SPA_ENV: ci,b2c
        run: |  
          ci-scripts/e2e-cypress.sh
  b2c_e2e_tests_3:
    name: E2E tests for B2C, 3rd job
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Run e2es
        env:         
          SPA_ENV: ci,b2c
        run: |
          ci-scripts/e2e-cypress.sh
  b2c_e2e_tests_4:
    name: E2E tests for B2C, 4th job
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Run e2es
        env:         
          SPA_ENV: ci,b2c
        run: |
          ci-scripts/e2e-cypress.sh
  b2c_e2e_tests_5:
    name: E2E tests for B2C, 5th job
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Run e2es
        env:         
          SPA_ENV: ci,b2c
        run: |
          ci-scripts/e2e-cypress.sh
  b2c_ssr_e2e_tests:
    name: E2E tests for SSR B2C
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Run e2es
        run: |
          ci-scripts/e2e-cypress.sh --ssr
  b2b_e2e_tests_1:
    name: E2E tests for B2B, 1st job
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Run e2es
        env:        
          SPA_ENV: ci,b2b
        run: |     
          ci-scripts/e2e-cypress.sh -s b2b
  b2b_e2e_tests_2:
    name: E2E tests for B2B, 2nd job
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Run e2es
        env:
          SPA_ENV: ci,b2b
        run: |     
          ci-scripts/e2e-cypress.sh -s b2b
  lighthouse:
    name: Lighthouse score validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install angular CLI
        run: npm install -g @angular/cli@v12-lts
      - name: Package installation
        run: yarn --frozen-lockfile
      - name: Run lighthouse score validation
        run: ci-scripts/lhci.sh