on:
  push:
    branches:
      - develop
      - epic/**
      - release/**
      - integration-libs/**
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}

name: Spartacus CI pipeline
jobs:
  no_retries: 
    name: No retries allowed. Please push an empty commit.
    runs-on: ubuntu-latest
    steps:
      - name: Force fail CI
        uses: actions/github-script@v5
        with:
          script: |
            core.setFailed('Please push an empty commit - git commit --allow-empty -m "Trigger Build"') 
        if: ${{ github.run_attempt > 1 }}
  unit_tests_core:
    needs: no_retries
    name: Unit tests for core Spartacus libs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install angular CLI
        run: npm install -g @angular/cli@v12-lts
      - name: Package installation
        run: yarn --frozen-lockfile
      - name: Run unit tests for core and storefront
        run: ci-scripts/unit-tests-core-lib.sh
  unit_tests_libs:
    needs: no_retries
    name: Unit tests for integration libs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install angular CLI
        run: npm install -g @angular/cli@v12-lts
      - name: Package installation
        run: yarn --frozen-lockfile
      - name: Run unit tests for libs
        run: ci-scripts/unit-tests.sh
  linting:
    needs: no_retries
    name: Validation checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install angular CLI
        run: npm install -g @angular/cli@v12-lts
      - name: Package installation
        run: yarn --frozen-lockfile
      - name: linting
        run: ci-scripts/validate-lint.sh
  b2c_e2e_tests:
    needs: no_retries
    name: E2E tests for B2C
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./
    strategy:
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/checkout@v2
      - name: Run e2es
        env: 
          SPA_ENV: ci,b2c
        run: |
          ci-scripts/e2e-cypress.sh
  b2c_ssr_e2e_tests:
    needs: no_retries
    name: E2E tests for SSR B2C
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Run e2es
        run: |
          ci-scripts/e2e-cypress.sh --ssr
  b2b_e2e_tests:
    needs: no_retries
    name: E2E tests for B2B
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./
    strategy:
      matrix:
        containers: [1, 2]
    steps:
      - uses: actions/checkout@v2
      - name: Run e2es
        env:
          SPA_ENV: ci,b2b
        run: |     
          ci-scripts/e2e-cypress.sh -s b2b
  lighthouse:
    needs: no_retries
    name: Lighthouse score validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install angular CLI
        run: npm install -g @angular/cli@v12-lts
      - name: Package installation
        run: yarn --frozen-lockfile
      - name: Run unit tests for core and storefront
        run: ci-scripts/lhci.sh
  ci_conclusion:
    needs: [no_retries, unit_tests_core, unit_tests_libs, linting, b2c_e2e_tests, b2c_ssr_e2e_tests, b2b_e2e_tests, lighthouse]
    name: CI Conclusion
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: test
        run: | 
          echo test ${{ github.event.state }}
          echo test ${{ github.event.status }}
          echo test ${{ toJSON(needs.no_retries) }}
          echo test ${{ toJSON(needs.b2c_e2e_tests) }}
      - name: Required CI failed
        uses: actions/github-script@v5
        with:
          script: |
            core.setFailed('CI failed')
        if: |
          needs.no_retries.result == 'failure' ||
          needs.unit_tests_core.result == 'failure' ||
          needs.unit_tests_libsresult == 'failure' ||
          needs.linting.result == 'failure' ||
          needs.b2c_e2e_tests.result == 'failure' ||
          needs.b2c_ssr_e2e_tests.result == 'failure' || 
          needs.b2b_e2e_tests.result == 'failure' || 
          needs.lighthouse.result == 'failure'