on:
  push:
    branches:
      - develop
      - epic/**
      - release/**
      - feature/**
      - integration-libs/**
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}

name: Spartacus CI pipeline
jobs:
  unit_tests_core:
    name: Unit tests for core Spartacus libs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'
      - name: Install angular CLI
        run: npm install -g @angular/cli@v12-lts
      - name: Package installation
        run: yarn --frozen-lockfile
      - name: Run unit tests for core Spartacus libs
        run: ci-scripts/unit-tests-core-lib.sh